base_url = "https://clip-template.vercel.app"
[book]
title = "lmm333's Clip"
description = "lmm333's Clip"
src = "content"
language = "zh"
authors = ["Mingming Lou"]

[output.html]
git-repository-url = "https://github.com/lmmsoft/clip"
edit-url-template = "https://github.com/lmmsoft/clip/edit/main/{path}"

[output.html.search]
enable = true

[output.markdown]
enable = true

[mail]
# false will diasble mail sending
enable = false
from_email = "lmm333@126.com"
from_name = "lmm333"
# you can set the mailjet contact list id here
# mailjet_contact_list_id = "17669"
# or directly set the to_email, seperated by comma
# or your can also set the environment variable TO_EMAIL
to_email = ""
